# You can put your preferred keybinds here
# https://wiki.hyprland.org/Configuring/Binds/
$mainMod=SUPER

unbind = Super, T
bind = $mainMod SHIFT, Q, exec, loginctl terminate-user ""
bind = $mainMod, T, exec, uwsm app -- alacritty
bind = $mainMod, B, exec, uwsm app -- app.zen_browser.zen
bind = $mainMod SHIFT, S, exec, uwsm app -- grimblast copy area
bindr = $mainMod, Super_L, exec, pkill fuzzel || fuzzel
bind = $mainMod, Tab, hyprexpo:expo, toggle

bind  = $mainMod, N, exec, swaync-client -t -sw

bind = $mainMod, code:10, workspace, 1
bind = $mainMod, code:11, workspace, 2
bind = $mainMod, code:12, workspace, 3
bind = $mainMod, code:13, workspace, 4
bind = $mainMod, code:14, workspace, 5
bind = $mainMod, code:15, workspace, 6
bind = $mainMod, code:16, workspace, 7
bind = $mainMod, code:17, workspace, 8
bind = $mainMod, code:18, workspace, 9

bind = $mainMod ALT, code:10, movetoworkspace, 1
bind = $mainMod ALT, code:11, movetoworkspace, 2
bind = $mainMod ALT, code:12, movetoworkspace, 3
bind = $mainMod ALT, code:13, movetoworkspace, 4
bind = $mainMod ALT, code:14, movetoworkspace, 5
bind = $mainMod ALT, code:15, movetoworkspace, 6
bind = $mainMod ALT, code:16, movetoworkspace, 7
bind = $mainMod ALT, code:17, movetoworkspace, 8
bind = $mainMod ALT, code:18, movetoworkspace, 9

bindle=, XF86MonBrightnessUp, exec, brightnessctl -q set '5%+'
bindle=, XF86MonBrightnessDown, exec, brightnessctl -q set '5%-'
