# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrulev2 = float, title:^(overskride)$
windowrulev2 = move 73% 15%, title:^(overskride)$
windowrulev2 = size 25% 50%, title:^(overskride)$

windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(nm-openconnect-auth-dialog)$
windowrulev2 = move 73% 15%, title:^(Network Connections)$
windowrulev2 = size 25% 50%, title:^(Network Connections)$

windowrulev2 = float, title:^(Easy Effects)$
windowrulev2 = float, title:^(Extension)(.*)$

# waybar
layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = ignorealpha 0.5, waybar

# swaync
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

layerrule = animation slide left, swaync-control-center
