[general]
import = [
  "/home/simon/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_moon.toml",
]
live_config_reload = true

[terminal]
shell = "/bin/fish"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = false
startup_mode = "Maximized"
