#!/bin/zsh

function sm() {
  if [ -z "$1" ]; then
    echo "No name provided"
    return 1
  fi

  DIR=$1
  NAME=$(basename $1)

  if tmux has-session -t $NAME 2>/dev/null; then
    tmux switch-client -t $NAME
    return 0
  fi

  tmux new-session -d -s $NAME
  tmux send-keys -t $NAME "cd $DIR; nvim" C-m
  tmux split-window -t $NAME -l 12 -d -c $DIR
  tmux switch-client -t $NAME
}
