[bar]
# Base height of the bar in pixels - all other sizes scale from this
size = 32

# Spacing between widgets within each section (in pixels)
spacing = 6

# Distance from the screen edge to the bar window (in pixels)
# screen_margin = 4

# Distance from the bar edge to the first/last section (in pixels)
inset = 4

# Border radius for the bar (percentage of bar height, 50% = fully rounded)
border_radius = 0

popover_offset = 6

[widgets]
center = []
right = [
  "custom-ddcutil",
  "media",
  "tray",
  { group = [
    "cpu",
    "gpu",
  ] },
  "battery",
  "quick_settings",
  { group = [
    "clock",
    "notifications",
  ] },
]
border_radius = 40
background_color = "#1a1b26"

[widgets.workspaces]
label_type = "numbers"

# Script output that updates every 10 minutes
[widgets.custom-ddcutil]
label = "Switch input"
icon = "output"
show_if = "niri msg -j outputs |grep UK02338064882"
on_click = "ddcutil -n UK02338064882 setvcp 60 1"
tooltip = "Switch input source"
max_chars = 20

[theme]
mode = "gtk"
accent = "#27a1b9"

[theme.states]
success = "#9ece6a"
warning = "#e0af68"
urgent = "#f7768e"

[theme.typography]
font_family = "Hack NF Propo, monospace"
